Update readme.html
YOURLS/YOURLS pull request #2758
Opened 2020-10-08 09:03 UTC by hitjethva

Add YOURLS installation link for Ubuntu 20.04 version.

2020-10-08 15:32 UTC, LeoColomb approved these changes
LGTM 👍 
Thx @hitjethva!

Side note: @hitjethva is also the author of the post.

2020-10-10 05:50 UTC, hitjethva commented
Please merge my pull request

2020-10-10 06:14 UTC, dgw requested changes
I thought about bowing to the impatience, but the ordering of these list items bugs me.

2020-10-10 06:14 UTC, dgw commented on readme.html
>  				<li><a href="https://computingforgeeks.com/how-to-install-yourls-your-own-url-shortener-on-ubuntu-18-04-bionic-beaver-linux/">How to install YOURLS on Ubuntu 18.04</a></li>
```suggestion
				<li><a href="https://www.rosehosting.com/blog/how-to-install-yourls-on-ubuntu-14-04/">How to Install YOURLS on Ubuntu 14.04</a></li>
				<li><a href="https://computingforgeeks.com/how-to-install-yourls-your-own-url-shortener-on-ubuntu-18-04-bionic-beaver-linux/">How to install YOURLS on Ubuntu 18.04</a></li>
                <li><a href="https://linuxbuz.com/linuxhowto/install-yourls-ubuntu-20-04">How to Install YOURLS URL Shortener on Ubuntu 20.04</a></li>
```

2020-10-10 06:27 UTC, hitjethva commented on readme.html
>  				<li><a href="https://computingforgeeks.com/how-to-install-yourls-your-own-url-shortener-on-ubuntu-18-04-bionic-beaver-linux/">How to install YOURLS on Ubuntu 18.04</a></li>
So how can I fix this?

2020-10-10 11:23 UTC, merged